spring.jpa:
  database: mysql
  hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  properties:
    hibernate:
      show-sql: true
      format_sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sk_fc_backend?serverTimezone=UTC&characterEncoding=UTF-8
  username: root
  password: root

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring.redis.url: redis://:p16eb8136279b2629c931d539b89c2491e9ef83cd2d9bc777afec1b649cb9b10d@ec2-3-224-198-214.compute-1.amazonaws.com:12979

spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="tbokvffz" password="gbS9_rezAH822V2L7fuadFQ4bcUefJjz";


    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: dory.srvs.cloudkafka.com:9094
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: dory.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: tbokvffz-alarm

