spring.jpa:
  database: mysql
  hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  properties:
    hibernate:
      show-sql: true
      format_sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sk_fc_backend?serverTimezone=UTC&characterEncoding=UTF-8
  username: root
  password: root

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

#spring.redis.url: redis://:p16eb8136279b2629c931d539b89c2491e9ef83cd2d9bc777afec1b649cb9b10d@ec2-3-224-198-214.compute-1.amazonaws.com:12979